'use strict';

// Config filename with path
const CONFIG_FILE = './config.json';

const logger = require('../utils/logger');

// Timezones
const timezones = [
	{title: 'Africa/Abidjan', value: 'Africa/Abidjan'},
	{title: 'Africa/Accra', value: 'Africa/Accra'},
	{title: 'Africa/Algiers', value: 'Africa/Algiers'},
	{title: 'Africa/Bissau', value: 'Africa/Bissau'},
	{title: 'Africa/Cairo', value: 'Africa/Cairo'},
	{title: 'Africa/Casablanca', value: 'Africa/Casablanca'},
	{title: 'Africa/Ceuta', value: 'Africa/Ceuta'},
	{title: 'Africa/El_Aaiun', value: 'Africa/El_Aaiun'},
	{title: 'Africa/Johannesburg', value: 'Africa/Johannesburg'},
	{title: 'Africa/Juba', value: 'Africa/Juba'},
	{title: 'Africa/Khartoum', value: 'Africa/Khartoum'},
	{title: 'Africa/Lagos', value: 'Africa/Lagos'},
	{title: 'Africa/Maputo', value: 'Africa/Maputo'},
	{title: 'Africa/Monrovia', value: 'Africa/Monrovia'},
	{title: 'Africa/Nairobi', value: 'Africa/Nairobi'},
	{title: 'Africa/Ndjamena', value: 'Africa/Ndjamena'},
	{title: 'Africa/Sao_Tome', value: 'Africa/Sao_Tome'},
	{title: 'Africa/Tripoli', value: 'Africa/Tripoli'},
	{title: 'Africa/Tunis', value: 'Africa/Tunis'},
	{title: 'Africa/Windhoek', value: 'Africa/Windhoek'},
	{title: 'America/Adak', value: 'America/Adak'},
	{title: 'America/Anchorage', value: 'America/Anchorage'},
	{title: 'America/Araguaina', value: 'America/Araguaina'},
	{title: 'America/Argentina/Buenos_Aires', value: 'America/Argentina/Buenos_Aires'},
	{title: 'America/Argentina/Catamarca', value: 'America/Argentina/Catamarca'},
	{title: 'America/Argentina/Cordoba', value: 'America/Argentina/Cordoba'},
	{title: 'America/Argentina/Jujuy', value: 'America/Argentina/Jujuy'},
	{title: 'America/Argentina/La_Rioja', value: 'America/Argentina/La_Rioja'},
	{title: 'America/Argentina/Mendoza', value: 'America/Argentina/Mendoza'},
	{title: 'America/Argentina/Rio_Gallegos', value: 'America/Argentina/Rio_Gallegos'},
	{title: 'America/Argentina/Salta', value: 'America/Argentina/Salta'},
	{title: 'America/Argentina/San_Juan', value: 'America/Argentina/San_Juan'},
	{title: 'America/Argentina/San_Luis', value: 'America/Argentina/San_Luis'},
	{title: 'America/Argentina/Tucuman', value: 'America/Argentina/Tucuman'},
	{title: 'America/Argentina/Ushuaia', value: 'America/Argentina/Ushuaia'},
	{title: 'America/Asuncion', value: 'America/Asuncion'},
	{title: 'America/Atikokan', value: 'America/Atikokan'},
	{title: 'America/Bahia', value: 'America/Bahia'},
	{title: 'America/Bahia_Banderas', value: 'America/Bahia_Banderas'},
	{title: 'America/Barbados', value: 'America/Barbados'},
	{title: 'America/Belem', value: 'America/Belem'},
	{title: 'America/Belize', value: 'America/Belize'},
	{title: 'America/Blanc-Sablon', value: 'America/Blanc-Sablon'},
	{title: 'America/Boa_Vista', value: 'America/Boa_Vista'},
	{title: 'America/Bogota', value: 'America/Bogota'},
	{title: 'America/Boise', value: 'America/Boise'},
	{title: 'America/Cambridge_Bay', value: 'America/Cambridge_Bay'},
	{title: 'America/Campo_Grande', value: 'America/Campo_Grande'},
	{title: 'America/Cancun', value: 'America/Cancun'},
	{title: 'America/Caracas', value: 'America/Caracas'},
	{title: 'America/Cayenne', value: 'America/Cayenne'},
	{title: 'America/Chicago', value: 'America/Chicago'},
	{title: 'America/Chihuahua', value: 'America/Chihuahua'},
	{title: 'America/Costa_Rica', value: 'America/Costa_Rica'},
	{title: 'America/Creston', value: 'America/Creston'},
	{title: 'America/Cuiaba', value: 'America/Cuiaba'},
	{title: 'America/Curacao', value: 'America/Curacao'},
	{title: 'America/Danmarkshavn', value: 'America/Danmarkshavn'},
	{title: 'America/Dawson', value: 'America/Dawson'},
	{title: 'America/Dawson_Creek', value: 'America/Dawson_Creek'},
	{title: 'America/Denver', value: 'America/Denver'},
	{title: 'America/Detroit', value: 'America/Detroit'},
	{title: 'America/Edmonton', value: 'America/Edmonton'},
	{title: 'America/Eirunepe', value: 'America/Eirunepe'},
	{title: 'America/El_Salvador', value: 'America/El_Salvador'},
	{title: 'America/Fort_Nelson', value: 'America/Fort_Nelson'},
	{title: 'America/Fortaleza', value: 'America/Fortaleza'},
	{title: 'America/Glace_Bay', value: 'America/Glace_Bay'},
	{title: 'America/Goose_Bay', value: 'America/Goose_Bay'},
	{title: 'America/Grand_Turk', value: 'America/Grand_Turk'},
	{title: 'America/Guatemala', value: 'America/Guatemala'},
	{title: 'America/Guayaquil', value: 'America/Guayaquil'},
	{title: 'America/Guyana', value: 'America/Guyana'},
	{title: 'America/Halifax', value: 'America/Halifax'},
	{title: 'America/Havana', value: 'America/Havana'},
	{title: 'America/Hermosillo', value: 'America/Hermosillo'},
	{title: 'America/Indiana/Indianapolis', value: 'America/Indiana/Indianapolis'},
	{title: 'America/Indiana/Knox', value: 'America/Indiana/Knox'},
	{title: 'America/Indiana/Marengo', value: 'America/Indiana/Marengo'},
	{title: 'America/Indiana/Petersburg', value: 'America/Indiana/Petersburg'},
	{title: 'America/Indiana/Tell_City', value: 'America/Indiana/Tell_City'},
	{title: 'America/Indiana/Vevay', value: 'America/Indiana/Vevay'},
	{title: 'America/Indiana/Vincennes', value: 'America/Indiana/Vincennes'},
	{title: 'America/Indiana/Winamac', value: 'America/Indiana/Winamac'},
	{title: 'America/Inuvik', value: 'America/Inuvik'},
	{title: 'America/Iqaluit', value: 'America/Iqaluit'},
	{title: 'America/Jamaica', value: 'America/Jamaica'},
	{title: 'America/Juneau', value: 'America/Juneau'},
	{title: 'America/Kentucky/Louisville', value: 'America/Kentucky/Louisville'},
	{title: 'America/Kentucky/Monticello', value: 'America/Kentucky/Monticello'},
	{title: 'America/La_Paz', value: 'America/La_Paz'},
	{title: 'America/Lima', value: 'America/Lima'},
	{title: 'America/Los_Angeles', value: 'America/Los_Angeles'},
	{title: 'America/Maceio', value: 'America/Maceio'},
	{title: 'America/Managua', value: 'America/Managua'},
	{title: 'America/Manaus', value: 'America/Manaus'},
	{title: 'America/Martinique', value: 'America/Martinique'},
	{title: 'America/Matamoros', value: 'America/Matamoros'},
	{title: 'America/Mazatlan', value: 'America/Mazatlan'},
	{title: 'America/Menominee', value: 'America/Menominee'},
	{title: 'America/Merida', value: 'America/Merida'},
	{title: 'America/Metlakatla', value: 'America/Metlakatla'},
	{title: 'America/Mexico_City', value: 'America/Mexico_City'},
	{title: 'America/Miquelon', value: 'America/Miquelon'},
	{title: 'America/Moncton', value: 'America/Moncton'},
	{title: 'America/Monterrey', value: 'America/Monterrey'},
	{title: 'America/Montevideo', value: 'America/Montevideo'},
	{title: 'America/Nassau', value: 'America/Nassau'},
	{title: 'America/New_York', value: 'America/New_York'},
	{title: 'America/Nipigon', value: 'America/Nipigon'},
	{title: 'America/Nome', value: 'America/Nome'},
	{title: 'America/Noronha', value: 'America/Noronha'},
	{title: 'America/North_Dakota/Beulah', value: 'America/North_Dakota/Beulah'},
	{title: 'America/North_Dakota/Center', value: 'America/North_Dakota/Center'},
	{title: 'America/North_Dakota/New_Salem', value: 'America/North_Dakota/New_Salem'},
	{title: 'America/Nuuk', value: 'America/Nuuk'},
	{title: 'America/Ojinaga', value: 'America/Ojinaga'},
	{title: 'America/Panama', value: 'America/Panama'},
	{title: 'America/Pangnirtung', value: 'America/Pangnirtung'},
	{title: 'America/Paramaribo', value: 'America/Paramaribo'},
	{title: 'America/Phoenix', value: 'America/Phoenix'},
	{title: 'America/Port-au-Prince', value: 'America/Port-au-Prince'},
	{title: 'America/Port_of_Spain', value: 'America/Port_of_Spain'},
	{title: 'America/Porto_Velho', value: 'America/Porto_Velho'},
	{title: 'America/Puerto_Rico', value: 'America/Puerto_Rico'},
	{title: 'America/Punta_Arenas', value: 'America/Punta_Arenas'},
	{title: 'America/Rainy_River', value: 'America/Rainy_River'},
	{title: 'America/Rankin_Inlet', value: 'America/Rankin_Inlet'},
	{title: 'America/Recife', value: 'America/Recife'},
	{title: 'America/Regina', value: 'America/Regina'},
	{title: 'America/Resolute', value: 'America/Resolute'},
	{title: 'America/Rio_Branco', value: 'America/Rio_Branco'},
	{title: 'America/Santarem', value: 'America/Santarem'},
	{title: 'America/Santiago', value: 'America/Santiago'},
	{title: 'America/Santo_Domingo', value: 'America/Santo_Domingo'},
	{title: 'America/Sao_Paulo', value: 'America/Sao_Paulo'},
	{title: 'America/Scoresbysund', value: 'America/Scoresbysund'},
	{title: 'America/Sitka', value: 'America/Sitka'},
	{title: 'America/St_Johns', value: 'America/St_Johns'},
	{title: 'America/Swift_Current', value: 'America/Swift_Current'},
	{title: 'America/Tegucigalpa', value: 'America/Tegucigalpa'},
	{title: 'America/Thule', value: 'America/Thule'},
	{title: 'America/Thunder_Bay', value: 'America/Thunder_Bay'},
	{title: 'America/Tijuana', value: 'America/Tijuana'},
	{title: 'America/Toronto', value: 'America/Toronto'},
	{title: 'America/Vancouver', value: 'America/Vancouver'},
	{title: 'America/Whitehorse', value: 'America/Whitehorse'},
	{title: 'America/Winnipeg', value: 'America/Winnipeg'},
	{title: 'America/Yakutat', value: 'America/Yakutat'},
	{title: 'America/Yellowknife', value: 'America/Yellowknife'},
	{title: 'Antarctica/Casey', value: 'Antarctica/Casey'},
	{title: 'Antarctica/Davis', value: 'Antarctica/Davis'},
	{title: 'Antarctica/DumontDUrville', value: 'Antarctica/DumontDUrville'},
	{title: 'Antarctica/Macquarie', value: 'Antarctica/Macquarie'},
	{title: 'Antarctica/Mawson', value: 'Antarctica/Mawson'},
	{title: 'Antarctica/Palmer', value: 'Antarctica/Palmer'},
	{title: 'Antarctica/Rothera', value: 'Antarctica/Rothera'},
	{title: 'Antarctica/Syowa', value: 'Antarctica/Syowa'},
	{title: 'Antarctica/Troll', value: 'Antarctica/Troll'},
	{title: 'Antarctica/Vostok', value: 'Antarctica/Vostok'},
	{title: 'Asia/Almaty', value: 'Asia/Almaty'},
	{title: 'Asia/Amman', value: 'Asia/Amman'},
	{title: 'Asia/Anadyr', value: 'Asia/Anadyr'},
	{title: 'Asia/Aqtau', value: 'Asia/Aqtau'},
	{title: 'Asia/Aqtobe', value: 'Asia/Aqtobe'},
	{title: 'Asia/Ashgabat', value: 'Asia/Ashgabat'},
	{title: 'Asia/Atyrau', value: 'Asia/Atyrau'},
	{title: 'Asia/Baghdad', value: 'Asia/Baghdad'},
	{title: 'Asia/Baku', value: 'Asia/Baku'},
	{title: 'Asia/Bangkok', value: 'Asia/Bangkok'},
	{title: 'Asia/Barnaul', value: 'Asia/Barnaul'},
	{title: 'Asia/Beirut', value: 'Asia/Beirut'},
	{title: 'Asia/Bishkek', value: 'Asia/Bishkek'},
	{title: 'Asia/Brunei', value: 'Asia/Brunei'},
	{title: 'Asia/Chita', value: 'Asia/Chita'},
	{title: 'Asia/Choibalsan', value: 'Asia/Choibalsan'},
	{title: 'Asia/Colombo', value: 'Asia/Colombo'},
	{title: 'Asia/Damascus', value: 'Asia/Damascus'},
	{title: 'Asia/Dhaka', value: 'Asia/Dhaka'},
	{title: 'Asia/Dili', value: 'Asia/Dili'},
	{title: 'Asia/Dubai', value: 'Asia/Dubai'},
	{title: 'Asia/Dushanbe', value: 'Asia/Dushanbe'},
	{title: 'Asia/Famagusta', value: 'Asia/Famagusta'},
	{title: 'Asia/Gaza', value: 'Asia/Gaza'},
	{title: 'Asia/Hebron', value: 'Asia/Hebron'},
	{title: 'Asia/Ho_Chi_Minh', value: 'Asia/Ho_Chi_Minh'},
	{title: 'Asia/Hong_Kong', value: 'Asia/Hong_Kong'},
	{title: 'Asia/Hovd', value: 'Asia/Hovd'},
	{title: 'Asia/Irkutsk', value: 'Asia/Irkutsk'},
	{title: 'Asia/Jakarta', value: 'Asia/Jakarta'},
	{title: 'Asia/Jayapura', value: 'Asia/Jayapura'},
	{title: 'Asia/Jerusalem', value: 'Asia/Jerusalem'},
	{title: 'Asia/Kabul', value: 'Asia/Kabul'},
	{title: 'Asia/Kamchatka', value: 'Asia/Kamchatka'},
	{title: 'Asia/Karachi', value: 'Asia/Karachi'},
	{title: 'Asia/Kathmandu', value: 'Asia/Kathmandu'},
	{title: 'Asia/Khandyga', value: 'Asia/Khandyga'},
	{title: 'Asia/Kolkata', value: 'Asia/Kolkata'},
	{title: 'Asia/Krasnoyarsk', value: 'Asia/Krasnoyarsk'},
	{title: 'Asia/Kuala_Lumpur', value: 'Asia/Kuala_Lumpur'},
	{title: 'Asia/Kuching', value: 'Asia/Kuching'},
	{title: 'Asia/Macau', value: 'Asia/Macau'},
	{title: 'Asia/Magadan', value: 'Asia/Magadan'},
	{title: 'Asia/Makassar', value: 'Asia/Makassar'},
	{title: 'Asia/Manila', value: 'Asia/Manila'},
	{title: 'Asia/Nicosia', value: 'Asia/Nicosia'},
	{title: 'Asia/Novokuznetsk', value: 'Asia/Novokuznetsk'},
	{title: 'Asia/Novosibirsk', value: 'Asia/Novosibirsk'},
	{title: 'Asia/Omsk', value: 'Asia/Omsk'},
	{title: 'Asia/Oral', value: 'Asia/Oral'},
	{title: 'Asia/Pontianak', value: 'Asia/Pontianak'},
	{title: 'Asia/Pyongyang', value: 'Asia/Pyongyang'},
	{title: 'Asia/Qatar', value: 'Asia/Qatar'},
	{title: 'Asia/Qostanay', value: 'Asia/Qostanay'},
	{title: 'Asia/Qyzylorda', value: 'Asia/Qyzylorda'},
	{title: 'Asia/Riyadh', value: 'Asia/Riyadh'},
	{title: 'Asia/Sakhalin', value: 'Asia/Sakhalin'},
	{title: 'Asia/Samarkand', value: 'Asia/Samarkand'},
	{title: 'Asia/Seoul', value: 'Asia/Seoul'},
	{title: 'Asia/Shanghai', value: 'Asia/Shanghai'},
	{title: 'Asia/Singapore', value: 'Asia/Singapore'},
	{title: 'Asia/Srednekolymsk', value: 'Asia/Srednekolymsk'},
	{title: 'Asia/Taipei', value: 'Asia/Taipei'},
	{title: 'Asia/Tashkent', value: 'Asia/Tashkent'},
	{title: 'Asia/Tbilisi', value: 'Asia/Tbilisi'},
	{title: 'Asia/Tehran', value: 'Asia/Tehran'},
	{title: 'Asia/Thimphu', value: 'Asia/Thimphu'},
	{title: 'Asia/Tokyo', value: 'Asia/Tokyo'},
	{title: 'Asia/Tomsk', value: 'Asia/Tomsk'},
	{title: 'Asia/Ulaanbaatar', value: 'Asia/Ulaanbaatar'},
	{title: 'Asia/Urumqi', value: 'Asia/Urumqi'},
	{title: 'Asia/Ust-Nera', value: 'Asia/Ust-Nera'},
	{title: 'Asia/Vladivostok', value: 'Asia/Vladivostok'},
	{title: 'Asia/Yakutsk', value: 'Asia/Yakutsk'},
	{title: 'Asia/Yangon', value: 'Asia/Yangon'},
	{title: 'Asia/Yekaterinburg', value: 'Asia/Yekaterinburg'},
	{title: 'Asia/Yerevan', value: 'Asia/Yerevan'},
	{title: 'Atlantic/Azores', value: 'Atlantic/Azores'},
	{title: 'Atlantic/Bermuda', value: 'Atlantic/Bermuda'},
	{title: 'Atlantic/Canary', value: 'Atlantic/Canary'},
	{title: 'Atlantic/Cape_Verde', value: 'Atlantic/Cape_Verde'},
	{title: 'Atlantic/Faroe', value: 'Atlantic/Faroe'},
	{title: 'Atlantic/Madeira', value: 'Atlantic/Madeira'},
	{title: 'Atlantic/Reykjavik', value: 'Atlantic/Reykjavik'},
	{title: 'Atlantic/South_Georgia', value: 'Atlantic/South_Georgia'},
	{title: 'Atlantic/Stanley', value: 'Atlantic/Stanley'},
	{title: 'Australia/Adelaide', value: 'Australia/Adelaide'},
	{title: 'Australia/Brisbane', value: 'Australia/Brisbane'},
	{title: 'Australia/Broken_Hill', value: 'Australia/Broken_Hill'},
	{title: 'Australia/Darwin', value: 'Australia/Darwin'},
	{title: 'Australia/Eucla', value: 'Australia/Eucla'},
	{title: 'Australia/Hobart', value: 'Australia/Hobart'},
	{title: 'Australia/Lindeman', value: 'Australia/Lindeman'},
	{title: 'Australia/Lord_Howe', value: 'Australia/Lord_Howe'},
	{title: 'Australia/Melbourne', value: 'Australia/Melbourne'},
	{title: 'Australia/Perth', value: 'Australia/Perth'},
	{title: 'Australia/Sydney', value: 'Australia/Sydney'},
	{title: 'CET', value: 'CET'},
	{title: 'CST6CDT', value: 'CST6CDT'},
	{title: 'EET', value: 'EET'},
	{title: 'EST', value: 'EST'},
	{title: 'EST5EDT', value: 'EST5EDT'},
	{title: 'Etc/GMT', value: 'Etc/GMT'},
	{title: 'Etc/GMT+1', value: 'Etc/GMT+1'},
	{title: 'Etc/GMT+10', value: 'Etc/GMT+10'},
	{title: 'Etc/GMT+11', value: 'Etc/GMT+11'},
	{title: 'Etc/GMT+12', value: 'Etc/GMT+12'},
	{title: 'Etc/GMT+2', value: 'Etc/GMT+2'},
	{title: 'Etc/GMT+3', value: 'Etc/GMT+3'},
	{title: 'Etc/GMT+4', value: 'Etc/GMT+4'},
	{title: 'Etc/GMT+5', value: 'Etc/GMT+5'},
	{title: 'Etc/GMT+6', value: 'Etc/GMT+6'},
	{title: 'Etc/GMT+7', value: 'Etc/GMT+7'},
	{title: 'Etc/GMT+8', value: 'Etc/GMT+8'},
	{title: 'Etc/GMT+9', value: 'Etc/GMT+9'},
	{title: 'Etc/GMT-1', value: 'Etc/GMT-1'},
	{title: 'Etc/GMT-10', value: 'Etc/GMT-10'},
	{title: 'Etc/GMT-11', value: 'Etc/GMT-11'},
	{title: 'Etc/GMT-12', value: 'Etc/GMT-12'},
	{title: 'Etc/GMT-13', value: 'Etc/GMT-13'},
	{title: 'Etc/GMT-14', value: 'Etc/GMT-14'},
	{title: 'Etc/GMT-2', value: 'Etc/GMT-2'},
	{title: 'Etc/GMT-3', value: 'Etc/GMT-3'},
	{title: 'Etc/GMT-4', value: 'Etc/GMT-4'},
	{title: 'Etc/GMT-5', value: 'Etc/GMT-5'},
	{title: 'Etc/GMT-6', value: 'Etc/GMT-6'},
	{title: 'Etc/GMT-7', value: 'Etc/GMT-7'},
	{title: 'Etc/GMT-8', value: 'Etc/GMT-8'},
	{title: 'Etc/GMT-9', value: 'Etc/GMT-9'},
	{title: 'Etc/UTC', value: 'Etc/UTC'},
	{title: 'Europe/Amsterdam', value: 'Europe/Amsterdam'},
	{title: 'Europe/Andorra', value: 'Europe/Andorra'},
	{title: 'Europe/Astrakhan', value: 'Europe/Astrakhan'},
	{title: 'Europe/Athens', value: 'Europe/Athens'},
	{title: 'Europe/Belgrade', value: 'Europe/Belgrade'},
	{title: 'Europe/Berlin', value: 'Europe/Berlin'},
	{title: 'Europe/Brussels', value: 'Europe/Brussels'},
	{title: 'Europe/Bucharest', value: 'Europe/Bucharest'},
	{title: 'Europe/Budapest', value: 'Europe/Budapest'},
	{title: 'Europe/Chisinau', value: 'Europe/Chisinau'},
	{title: 'Europe/Copenhagen', value: 'Europe/Copenhagen'},
	{title: 'Europe/Dublin', value: 'Europe/Dublin'},
	{title: 'Europe/Gibraltar', value: 'Europe/Gibraltar'},
	{title: 'Europe/Helsinki', value: 'Europe/Helsinki'},
	{title: 'Europe/Istanbul', value: 'Europe/Istanbul'},
	{title: 'Europe/Kaliningrad', value: 'Europe/Kaliningrad'},
	{title: 'Europe/Kiev', value: 'Europe/Kiev'},
	{title: 'Europe/Kirov', value: 'Europe/Kirov'},
	{title: 'Europe/Lisbon', value: 'Europe/Lisbon'},
	{title: 'Europe/London', value: 'Europe/London'},
	{title: 'Europe/Luxembourg', value: 'Europe/Luxembourg'},
	{title: 'Europe/Madrid', value: 'Europe/Madrid'},
	{title: 'Europe/Malta', value: 'Europe/Malta'},
	{title: 'Europe/Minsk', value: 'Europe/Minsk'},
	{title: 'Europe/Monaco', value: 'Europe/Monaco'},
	{title: 'Europe/Moscow', value: 'Europe/Moscow'},
	{title: 'Europe/Oslo', value: 'Europe/Oslo'},
	{title: 'Europe/Paris', value: 'Europe/Paris'},
	{title: 'Europe/Prague', value: 'Europe/Prague'},
	{title: 'Europe/Riga', value: 'Europe/Riga'},
	{title: 'Europe/Rome', value: 'Europe/Rome'},
	{title: 'Europe/Samara', value: 'Europe/Samara'},
	{title: 'Europe/Saratov', value: 'Europe/Saratov'},
	{title: 'Europe/Simferopol', value: 'Europe/Simferopol'},
	{title: 'Europe/Sofia', value: 'Europe/Sofia'},
	{title: 'Europe/Stockholm', value: 'Europe/Stockholm'},
	{title: 'Europe/Tallinn', value: 'Europe/Tallinn'},
	{title: 'Europe/Tirane', value: 'Europe/Tirane'},
	{title: 'Europe/Ulyanovsk', value: 'Europe/Ulyanovsk'},
	{title: 'Europe/Uzhgorod', value: 'Europe/Uzhgorod'},
	{title: 'Europe/Vienna', value: 'Europe/Vienna'},
	{title: 'Europe/Vilnius', value: 'Europe/Vilnius'},
	{title: 'Europe/Volgograd', value: 'Europe/Volgograd'},
	{title: 'Europe/Warsaw', value: 'Europe/Warsaw'},
	{title: 'Europe/Zaporozhye', value: 'Europe/Zaporozhye'},
	{title: 'Europe/Zurich', value: 'Europe/Zurich'},
	{title: 'HST', value: 'HST'},
	{title: 'Indian/Chagos', value: 'Indian/Chagos'},
	{title: 'Indian/Christmas', value: 'Indian/Christmas'},
	{title: 'Indian/Cocos', value: 'Indian/Cocos'},
	{title: 'Indian/Kerguelen', value: 'Indian/Kerguelen'},
	{title: 'Indian/Mahe', value: 'Indian/Mahe'},
	{title: 'Indian/Maldives', value: 'Indian/Maldives'},
	{title: 'Indian/Mauritius', value: 'Indian/Mauritius'},
	{title: 'Indian/Reunion', value: 'Indian/Reunion'},
	{title: 'MET', value: 'MET'},
	{title: 'MST', value: 'MST'},
	{title: 'MST7MDT', value: 'MST7MDT'},
	{title: 'PST8PDT', value: 'PST8PDT'},
	{title: 'Pacific/Apia', value: 'Pacific/Apia'},
	{title: 'Pacific/Auckland', value: 'Pacific/Auckland'},
	{title: 'Pacific/Bougainville', value: 'Pacific/Bougainville'},
	{title: 'Pacific/Chatham', value: 'Pacific/Chatham'},
	{title: 'Pacific/Chuuk', value: 'Pacific/Chuuk'},
	{title: 'Pacific/Easter', value: 'Pacific/Easter'},
	{title: 'Pacific/Efate', value: 'Pacific/Efate'},
	{title: 'Pacific/Enderbury', value: 'Pacific/Enderbury'},
	{title: 'Pacific/Fakaofo', value: 'Pacific/Fakaofo'},
	{title: 'Pacific/Fiji', value: 'Pacific/Fiji'},
	{title: 'Pacific/Funafuti', value: 'Pacific/Funafuti'},
	{title: 'Pacific/Galapagos', value: 'Pacific/Galapagos'},
	{title: 'Pacific/Gambier', value: 'Pacific/Gambier'},
	{title: 'Pacific/Guadalcanal', value: 'Pacific/Guadalcanal'},
	{title: 'Pacific/Guam', value: 'Pacific/Guam'},
	{title: 'Pacific/Honolulu', value: 'Pacific/Honolulu'},
	{title: 'Pacific/Kiritimati', value: 'Pacific/Kiritimati'},
	{title: 'Pacific/Kosrae', value: 'Pacific/Kosrae'},
	{title: 'Pacific/Kwajalein', value: 'Pacific/Kwajalein'},
	{title: 'Pacific/Majuro', value: 'Pacific/Majuro'},
	{title: 'Pacific/Marquesas', value: 'Pacific/Marquesas'},
	{title: 'Pacific/Nauru', value: 'Pacific/Nauru'},
	{title: 'Pacific/Niue', value: 'Pacific/Niue'},
	{title: 'Pacific/Norfolk', value: 'Pacific/Norfolk'},
	{title: 'Pacific/Noumea', value: 'Pacific/Noumea'},
	{title: 'Pacific/Pago_Pago', value: 'Pacific/Pago_Pago'},
	{title: 'Pacific/Palau', value: 'Pacific/Palau'},
	{title: 'Pacific/Pitcairn', value: 'Pacific/Pitcairn'},
	{title: 'Pacific/Pohnpei', value: 'Pacific/Pohnpei'},
	{title: 'Pacific/Port_Moresby', value: 'Pacific/Port_Moresby'},
	{title: 'Pacific/Rarotonga', value: 'Pacific/Rarotonga'},
	{title: 'Pacific/Tahiti', value: 'Pacific/Tahiti'},
	{title: 'Pacific/Tarawa', value: 'Pacific/Tarawa'},
	{title: 'Pacific/Tongatapu', value: 'Pacific/Tongatapu'},
	{title: 'Pacific/Wake', value: 'Pacific/Wake'},
	{title: 'Pacific/Wallis', value: 'Pacific/Wallis'},
	{title: 'WET', value: 'WET'}
];

// Questions
const questions = [
    {
        type: 'text',
        name: 'url',
        message: 'Enter the WebCall URL to update DDNS IP:',
    },
    {
        type: 'confirm',
        name: 'printlogs',
        message: 'Print logs in console?',
        initial: false,
    },
    {
        type: 'confirm',
        name: 'iscronjob',
        message: 'Do you want to set it as a cronjob?',
        initial: false,
    },
    {
        type: prev => prev ? 'number' : null,
        name: 'cronjob',
        message: 'Every how many minutes the scheduled task to be executed?',
        initial: 15,
        min: 1,
        max: 60,
    },
    {
        type: prev => prev ? 'autocomplete' : null,
        name: 'timezone',
        message: 'Enter the timezone',
        choices: timezones,
        initial: 'America/Hermosillo'
    }
];

// Start to set the config
module.exports = {
    getData: async (reset=false) => {
        try {
            const filer = require('../utils/filer');
            // Check the current stored config-data
            const currentConfig = filer.getDataFromFile(CONFIG_FILE);
			if (!currentConfig || currentConfig.toString().trim()==='') {
				logger.warn(`${CONFIG_FILE} is empty`, true);
			}
			// Parse the current config-data to JSON
			let currentConfigJSON;
			try {
				currentConfigJSON = JSON.parse(currentConfig);
			} catch (ex) {
				logger.warn(`${CONFIG_FILE} has invalid JSON syntax`, true);
			}

            // Return current loaded config if this exists while reset is false
            if (!reset && currentConfigJSON && currentConfigJSON.url) return currentConfigJSON;

            // Prompt the questions and save the answers of the config to the JSON local-file
            const prompter = require('../utils/prompter');
            const answers = await prompter.ask(questions);

            // Config-data which will be stored to the loca JSON-file
            let configData;

            // After finish answering the questions, save it
            if (answers) {
                // Spread the answers with the config data
                configData = {...answers};
        
                // Generate the cronjob format syntax
                if (configData.iscronjob) {
                    configData.cronjob = '*/' + configData.cronjob + ' * * * *';
                }
                delete configData.iscronjob;
        
                // Save the config-data with JSON format to a local file
                const saved = filer.saveDataToFile(JSON.stringify(configData,null,2), CONFIG_FILE);
				if (!saved) throw Error(`Couldn't save the ${CONFIG_FILE} file.`)
            }
            return configData;

        } catch (err) {
            logger.error(err.message||err, true);
        }
    }
}
